name: Build Check

on:
  pull_request:
    branches: [ develop ] # Укажите здесь вашу основную ветку, если она не main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*' # Использование последней LTS-версии Node.js

    - name: Install dependencies
      run: npm install

    - name: Run make deploy
      run: make deploy
